apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountkey: BASE_64_ENCODED_STORAGE_ACCOUNT_KEY
  azurestorageaccountname: BASE_64_ENCODED_STORAGE_ACCOUNT_NAME
